name: build & deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Install and Build
      run: |
        npm install
        npm run docs:build
        
    - name: Deploy Build Files
      env:
        # You should enroll ACEESS_TOKEN to repository's secret
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      run: |
        cd .vitepress/dist
        git config --global user.email "cnsalit@cnsa.hs.kr"
        git config --global user.name "cnsalit-actions"
        git init
        git add -A
        git commit -m 'Chore: 렌더링 vuepress'
        git push -f https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages